export const QUERY_REQUEST = 'QUERY_REQUEST';
export const QUERY_SUCCESS = 'QUERY_SUCCESS';
export const QUERY_FAILURE = 'QUERY_FAILURE';
export const QUERY_SAVE = 'QUERY_SAVE';
export const QUERY_DELETE = 'QUERY_DELETE';

export const TABLE_SELECT = 'TABLE_SELECT';
export const TABLE_REQUEST = 'TABLE_REQUEST';
export const TABLE_SUCCESS = 'TABLE_SUCCESS';
export const TABLE_FAILURE = 'TABLE_FAILURE';
export const TABLE_INVALIDATE = 'TABLE_INVALIDATE';

export const COLUMN_REQUEST = 'COLUMN_REQUEST';
export const COLUMN_SUCCESS = 'COLUMN_SUCCESS';
export const COLUMN_FAILURE = 'COLUMN_FAILURE';

export const SAVE_TEXT = 'SAVE_TEXT';

export const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE';
